### PR TITLE
Fuzz: verify that roundtripping f64 through string results in the same value

### PR DESCRIPTION
**Pull request by Shnatsel**

### CODE REVIEW

**Comment by aldanor** [comment]
Looks good! What is the random float64 generator used by the fuzzer? I.e. would it often emit super large and super small floats? (in case it does you might also use ryu serializer because it will use scientific notation and standard library's to-string will not - thus giving you free code paths).

**Comment by Shnatsel** [comment]
> would it often emit super large and super small floats? 

It will, if it notices that they trigger different code paths. I'll copy the ryu setup from the exhaustive f32 roundtrip test and see if that changes anything.

**Comment by aldanor** [comment]
Thanks!

**Comment by aldanor** [comment]
@Shnatsel I kicked off fuzz testing 4 months ago and totally forgot about it...

```
#1099511627776	pulse  cov: 149 ft: 195 corp: 71/561b lim: 4096 exec/s: 148343 rss: 538Mb
```

1.1 trillion checks for each of the fuzz tests... I think it's safe to say it's safe enough 🤣

**Pull request merged**
